### ISSUE TITLE
Issue running the live-demo.py script ?

### ISSUE THREAD

**Issue by basicvisual** [stefanopini/simple-HRNet#12]
Hello 
I am having troubles in executing , the live-demo script. I get the following , issue .  I am using the following pre trained weight `pose_hrnet_w48_384x288.pth`
I have not come across this issue before 

```
python3.6 scripts/live-demo.py --filename /home/test/simple-HRNet/test.mp4 
cuda:0
Traceback (most recent call last):
  File "scripts/live-demo.py", line 99, in <module>
    main(**args.__dict__)
  File "scripts/live-demo.py", line 57, in main
    pts = model.predict(frame)
  File "/home/test/simple-HRNet/SimpleHRNet.py", line 124, in predict
    return self._predict_single(image)
  File "/home/test/simple-HRNet/SimpleHRNet.py", line 184, in _predict_single
    shape=(self.resolution[0] // 4, self.resolution[1] // 4))
TypeError: Required argument 'dims' (pos 2) not found

```

**Comment by stefanopini** [comment]
The error is caused by numpy whose version is earlier than the required (>=1.16).
Have you run `pip install -r requirements.txt`?

In any case, I've just updated the code and now it **should** work up to numpy 1.14.

For the second error, there was an error in the example. The correct last line is `joints = model.predict(image)`.

**Comment by basicvisual** [comment]
Thank you !
