### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by EDGSCOUT** [stefanopini/simple-HRNet#19]
(simpleHR) scout@scout-Aspire-GX-781:/media/scout/26869a43-e371-4f24-97af-3bbd01078e2d/scout/Documents/simple-HRNet-master$ python scripts/train_coco.py
cuda:0

Starting experiment `20190828_0938` @ 2019-08-28 09:38:20

Loading train and validation datasets...
loading annotations into memory...
Done (t=7.03s)
creating index...
index created!
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 118287/118287 [00:19<00:00, 5930.78it/s]

COCO dataset loaded!
loading annotations into memory...
Done (t=0.26s)
creating index...
index created!
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5000/5000 [00:00<00:00, 6104.34it/s]

COCO dataset loaded!
cuda:0

Training started @ 2019-08-28 09:38:56

Epoch 0 of 200 @ 2019-08-28 09:38:56
Training:   0%|                                                                                                                                                            | 0/149813 [00:00<?, ?it/s]Traceback (most recent call last):
  File "scripts/train_coco.py", line 153, in <module>
    main(**args.__dict__)
  File "scripts/train_coco.py", line 111, in main
    train.run()
  File "/media/scout/26869a43-e371-4f24-97af-3bbd01078e2d/scout/Documents/simple-HRNet-master/training/Train.py", line 348, in run
    self._train()
  File "/media/scout/26869a43-e371-4f24-97af-3bbd01078e2d/scout/Documents/simple-HRNet-master/training/COCO.py", line 131, in _train
    for step, (image, target, target_weight, joints_data) in enumerate(tqdm(self.dl_train, desc='Training')):
  File "/home/scout/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1005, in __iter__
    for obj in iterable:
  File "/home/scout/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/scout/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 682, in __init__
    w.start()
  File "/home/scout/anaconda3/envs/simpleHR/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/scout/anaconda3/envs/simpleHR/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/scout/anaconda3/envs/simpleHR/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/scout/anaconda3/envs/simpleHR/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/scout/anaconda3/envs/simpleHR/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by EDGSCOUT** [comment]
I  change the self.starting_epoch = -1 the original starting_epoch is 0

**Comment by stefanopini** [comment]
What `batch_size` and `num_workers` did you use?
Have you checked the RAM occupancy?
Do you have a Nvidia GPU?

**Comment by EDGSCOUT** [comment]
> What `batch_size` and `num_workers` did you use?
> Have you checked the RAM occupancy?
> Do you have a Nvidia GPU?

Thank you very much~
