### ISSUE TITLE
Number of keypoints

### ISSUE THREAD

**Issue by m5823779** [stefanopini/simple-HRNet#57]
COCOEvaluator support NUM_KEYPOINTS != 17
-------------------------------------------------------------------------------------------------------------------------------------------
I have created my own dataset, but it is different from COCO (The number of keypoints is not 17 but 4)
how can I adjust so that the COCOEvaluator can support NUM_KEYPOINTS != 17 

Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *keypoints*
Traceback (most recent call last):
  File "scripts/train_coco.py", line 153, in <module>
    main(**args.__dict__)
  File "scripts/train_coco.py", line 111, in main
    train.run()
  File "/home/acer/simple-HRNet/training/Train.py", line 348, in run
    self._train()
  File "/home/acer/simple-HRNet/training/COCO.py", line 189, in _train
    all_preds, all_boxes, image_paths, output_dir=self.log_path)
  File "/home/acer/simple-HRNet/datasets/COCO.py", line 384, in evaluate_overall_accuracy
    info_str = self._do_python_keypoint_eval(res_file)
  File "/home/acer/simple-HRNet/datasets/COCO.py", line 576, in _do_python_keypoint_eval
    coco_eval.evaluate()
  File "/home/acer/.local/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 149, in evaluate
    for imgId in p.imgIds
  File "/home/acer/.local/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 150, in <dictcomp>
    for catId in catIds}
  File "/home/acer/.local/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 229, in computeOks
    e = (dx**2 + dy**2) / vars / (gt['area']+np.spacing(1)) / 2
ValueError: operands could not be broadcast together with shapes (4,) (17,)

**Comment by stefanopini** [comment]
Hi!

That code will only work with COCO images because it is part of a tool made by coco authors called [cocoapi/pycocotools](https://github.com/cocodataset/cocoapi/tree/master/PythonAPI/pycocotools).
As you can see [here](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py#L195-L196), there are variables that is loaded from the COCO dataset so it won't work on a custom one.

My suggestion is to remove that evaluation (which is specific for the COCO dataset) from the training split or to open an issue in the cocoapi repository.
