### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified (ffmpeg issue)

### ISSUE THREAD

**Issue by temptitle** [stefanopini/simple-HRNet#73]
I tried to run python live-demo.py --filename

And got this error (on my local pc and on colab), do you have any suggestions?
(os.path.isfile) return true 

Traceback (most recent call last):
  File "live-demo.py", line 189, in <module>
    main(**args.__dict__)
  File "live-demo.py", line 39, in [main]( @ #[url]([url](url)))
    rotation_code = check_video_rotation(filename)
  File "C:\Users\мiшель\Desktop\Pose Estimation\simple-HRNet\misc\visualization.py", line 276, in check_video_rotation
    meta_dict = ffmpeg.probe(filename)
  File "C:\Users\мiшель\AppData\Local\Programs\Python\Python36\lib\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\мiшель\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\мiшель\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

error on colab
Traceback (most recent call last):
  File "scripts/live-demo.py", line 185, in <module>
    main(**args.__dict__)
  File "scripts/live-demo.py", line 35, in main
    rotation_code = check_video_rotation(filename)
  File "/simple-HRNet/misc/visualization.py", line 276, in check_video_rotation
    meta_dict = ffmpeg.probe(filename)
  File "/usr/local/lib/python3.6/dist-packages/ffmpeg/_probe.py", line 23, in probe
    raise Error('ffprobe', out, err)
ffmpeg._run.Error: ffprobe error (see stderr output for detail)

**Comment by temptitle** [comment]
Problem was in incorrect installation of ffmpeg 

http://blog.gregzaal.com/how-to-install-ffmpeg-on-windows/

**Comment by stefanopini** [comment]
Thank you for updating the issue and sharing the solution!

**Comment by PeterInTheHouse** [comment]
I found that the website can't download package, so I downloaded it from the official website:
[https://www.ffmpeg.org/download.html#build-windows](url)
Download the window version:
[https://www.gyan.dev/ffmpeg/builds/](url)
