### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: / FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by woodylin89** [stefanopini/simple-HRNet#96]
1)
While I type "python scripts/live-demo.py --camera_id 0" 

report:

08:26:17 ::    Helper     ::   INFO   :: Running VidGear Version: 0.2.5
device: 'cpu'
Traceback (most recent call last):
  File "C:\Users\User\Desktop\simple hrnet\simple-HRNet\scripts\live-demo.py", line 185, in <module>
    main(**args.__dict__)
  File "C:\Users\User\Desktop\simple hrnet\simple-HRNet\scripts\live-demo.py", line 55, in main
    model = SimpleHRNet(
  File "C:\Users\User\Desktop\simple hrnet\simple-HRNet\SimpleHRNet.py", line 131, in __init__
    self.detector = YOLOv3(model_def=yolo_model_def,
  File "C:\Users\User\Desktop\simple hrnet\simple-HRNet\models\detectors\YOLOv3.py", line 105, in __init__
    self.model.load_darknet_weights(weights_path)
  File "C:\Users\User\Desktop\simple hrnet\simple-HRNet\models\detectors\yolo\models.py", line 273, in load_darknet_weights
    with open(weights_path, "rb") as f:
PermissionError: [Errno 13] Permission denied: './models/detectors/yolo/weights/yolov3.weights'

2) python scripts/live-demo.py --filename AAA.mp4 (AAA is my video name AAA.mp4)

report :
08:30:51 ::    Helper     ::   INFO   :: Running VidGear Version: 0.2.5
Traceback (most recent call last):
  File "scripts/live-demo.py", line 185, in <module>
    main(**args.__dict__)
  File "scripts/live-demo.py", line 35, in main
    rotation_code = check_video_rotation(filename)
  File "C:\Users\User\Desktop\simple hrnet\simple-HRNet\misc\visualization.py", line 276, in check_video_rotation
    meta_dict = ffmpeg.probe(filename)
  File "C:\Users\User\anaconda3\envs\simplehrnet_python\lib\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\User\anaconda3\envs\simplehrnet_python\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\User\anaconda3\envs\simplehrnet_python\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 

Plese Help

![111](https://user-images.githubusercontent.com/103179130/165652704-051b0875-f171-4c6e-9e37-106b0d523a5e.png)
![222](https://user-images.githubusercontent.com/103179130/165653145-a40daca0-55eb-405e-93d9-070054e00626.png)

**Comment by stefanopini** [comment]
Hi @woodylin89 , my apologies for the late reply, I completely missed your issue.

The two issues seem related to two different problems.
1. I would check the file yolo weights are in the specified folder and the current user has access to it
2. It seems the path to your video is incorrect. Is the file AAA.mp4 in the simple-HRNet folder?

I'm closing the issue, please open it again if you're still interested in solving the problems you faced.
